#!/usr/bin/env perl

use strict;

die "Exactly one argument is required.\n" if @ARGV != 1;

my $modulus = $ARGV[0];

if (!($modulus =~ /^[0-9]+$/ && $modulus > 0)) {
   die "Argument must be natural number.\n";
}

open(my $out, ">", "${modulus}.neato");

print $out "digraph G {\n";

for(my $i = 0; $i < $modulus; ++$i) {
   my $next = ($i * $i) % $modulus;
   print $out "   $i -> $next;\n";
}

print $out "}\n";

